### PR TITLE
Clean up unknown environments

### PR DESCRIPTION
**Pull request by cbowman0**
When a branch no longer exist in the git repository, the dir should be removed from the basedir.  r10k does remove all unknown directories in the managed directory.  g10k does not.  This patch attempts to correct this.

### CODE REVIEW

**Comment by xorpaul** [comment]
Thanks. I'll have a look at this next week.

**Comment by cbowman0** [comment]
Hi @xorpaul, were you able to look into this?

**Comment by xorpaul** [comment]
I've used your version and added fileglobing depending if your g10k source is using a `prefix` or not.

The reason for this is that I'm using multiple teams/config sources deploying Puppet environments to the same base directory.

``` /tmp/g10k/foo_test
 /tmp/g10k/foo_live
 /tmp/g10k/bar_qa
 /tmp/g10k/bar_live
```
With your version all other teams/source Puppet environment folders would be deleted.

Check out:
https://github.com/xorpaul/g10k/commit/cc2eff1efca7c5f0b7a9ff2d050564bc623b7a42

I'm basically just checking if `prefix` is set and then only considering the relevant Puppet environment directory for deletion.

**Comment by cbowman0** [comment]
That makes sense.

I tested your changes and they work for me.

**Comment by cbowman0** [comment]
Do you need me to do anything in order to complete this request?

**Comment by xorpaul** [comment]
Nope, I'll merge it when I can find the time to do it.

**Pull request closed without merging**
